# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoirs', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ManyToManyField(to='memoirs.Location'),
        ),
    ]
