# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoirs', '0004_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memoirs.Category'),
        ),
    ]
