# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoirs', '0005_image_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='details',
        ),
    ]
